### ISSUE TITLE
Add our own coins?

### ISSUE THREAD

**Issue by RedPlumpTomato** [JM1F/Cryptocurrency-Widget#2]
Very nice app!. Any chance we can add our own coins to it? Perhaps a context menu, right click, remove coins, then add a coin of our choice?

Also, the ability to resize the window would be nice :)

Thank you!

**Comment by JM1F** [comment]
Adding coins feature could take a little while but it is a excellent idea, however there are some restrictions that would need to be kept in mind due to the API restricting the amount of calls you can make per IP address.

If you would like to request certain coins to put in currently feel free to post here with thier names.

As for the ability to resize the window, could you please tell me what you would like this for. (e.g. text larger) So I can get an idea on what is required.

Thanks for the suggestions!
